### ISSUE TITLE
Working app started crashing - java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found

### ISSUE THREAD

**Issue by vjrathod** [tanersener/mobile-ffmpeg#340] opened 2020-02-09 22:14 UTC
**Description**
App was working before but it has started crashing. I checked with exact code that was working before.
It crash on calling "Config.enableLogCallback" method.

I am using - 'com.arthenica:mobile-ffmpeg-full-gpl:4.2.2.LTS'

**Expected behavior**
It should not crash, as it was working perfectly.

**Current behavior**
App crashing

**Logs**
java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:40)
        at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:118)
        at com.arthenica.mobileffmpeg.Config.enableLogCallback(Config.java:212)
        at com.lim.performer.VideoFastMotion.setCallBackLog(VideoFastMotion.kt:102)
        at com.lim.performer.VideoFastMotion.convert(VideoFastMotion.kt:73)
        at com.lim.activity.BaseActivity.editVideoSpeed(BaseActivity.java:342)
        at com.lim.activity.ProcessVideoActivity.editVideo(ProcessVideoActivity.kt:188)
        at com.lim.activity.ProcessVideoActivity$clickListener$1.onClick(ProcessVideoActivity.kt:177)
        at com.lim.databinding.LayoutToolbarBindingImpl$OnClickListenerImpl.onClick(LayoutToolbarBindingImpl.java:125)
        at android.view.View.performClick(View.java:7339)
        at android.view.View.performClickInternal(View.java:7305)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27787)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by tanersener** [comment] 2020-02-09 22:42
Duplicate of #249, #298

**Closed** 2020-02-18 20:59 UTC
Labels: duplicate
