### ISSUE TITLE
fdsan fails on closing SAF file descriptor at the end

### ISSUE THREAD

**Issue by alexcohn** [tanersener/mobile-ffmpeg#634] opened 2020-12-28 17:28 UTC
[**Description**](https://github.com/tanersener/mobile-ffmpeg/pull/440#issuecomment-751403932)
This is the ffprobe command executed:
```
[-print_format, json=c=1, -show_chapters, -loglevel, quiet, -show_entries, format=duration, -show_entries, format_tags=artist,title,album, -show_entries, stream_tags=artist,title,album, -select_streams, a, -i, saf:69/28 - Kapitel 8_ Mondmänner und Katzonauten.mp3]
```
And this is the sigabrt crash:
```
A/libc: fdsan: attempted to close file descriptor 69, expected to be unowned, actually owned by ParcelFileDescriptor 0xcd37e73
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14414 (DefaultDispatch), pid 14385 (audiobook.debug)
Tested targeting android 11 using a pixel 4.
```

**Expected behavior**
`fdsan` should allow the SAF descriptor to be closed

**Current behavior**
`fdsan` considers the SAF descriptor as owned by ParcelFileDescriptor

**Environment**
 - Platform: `Android`
 - Architecture: `arm64-v8a`
 - Version `4.4`
 - Source branch `development`
 - Android Studio version `4.1`
 - Android NDK version `21.1`

**Other**
Confirmed on emulator.

**Comment by tanersener** [comment] 2021-01-25 12:27
These two pages, [File descriptor sanitizer (fdsan)](https://developer.android.com/about/versions/11/behavior-changes-all) and [fdsan](https://android.googlesource.com/platform/bionic/+/master/docs/fdsan.md) explain what has changed in Android 11 (API Level 30) and what must be done to fix this.

Unfortunately, they recommend to use `fdsan` to close the native fds. But the problem is, fdsan is only available on API Level 29 >=. So, using `fdsan` directly is not possible. Any suggestions?

**Comment by tanersener** [comment] 2021-01-25 21:04
Apparently, `ParcelFileDescriptor.close()` method that we call inside `Config.closeParcelFileDescriptor` is already closing the `fd`. If we close the `fd` again `fdsan` complains that we're double-closing it. So, I'll remove the `close` from the native method to fix this.

`E/fdsan: double-close of file descriptor 64 detected`

**Comment by tanersener** [comment] 2021-04-13 19:32
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit). This issue is fixed there.

**Closed by tanersener** 2021-04-13 19:32 UTC
Labels: incompatibility, wontfix
