### ISSUE TITLE
Adding audio to video 

### ISSUE THREAD

**Issue by gururajKp** [tanersener/mobile-ffmpeg#240] opened 2019-09-18 05:39 UTC
**Description**
Hi I want to add an audio to to video. Audio's length is shorter that video.

**Expected behavior**
Audio should be repeated til the video ends.

**Current behavior**
Currently audio ends but video ll play till the end without any audio. I want audio should play till video ends which I added. Audio should loop.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.com) and insert the link here.

**Environment**

 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]

 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by tanersener** [comment] 2019-09-18 07:29
Duplicate of #235

**Comment by tanersener** [comment] 2019-09-18 07:37
@gururajKp You can find the answer of this question on `google`. If you can't then [please ask ffmpeg questions to ffmpeg-user@ffmpeg.org](https://github.com/tanersener/mobile-ffmpeg/issues/130). Remember that I'm the author of this project but I don't have all the answers.

**Closed** 2019-11-03 23:00 UTC
Labels: duplicate, ffmpeg-question
