### ISSUE TITLE
Can some one tell me how to reduce apk size?

### ISSUE THREAD

**Issue by DevElango** [tanersener/mobile-ffmpeg#448] opened 2020-06-13 07:27 UTC
i just need to mix audio and video. i done it, but the apk size is to big.

**Comment by tanersener** [comment] 2020-06-15 23:50
See [How to decrease binary size](https://github.com/tanersener/mobile-ffmpeg/wiki/How-to-decrease-binary-size).

**Comment by abinav-baskar** [comment] 2020-06-16 15:38
Could you elaborate on the guide you've given? Is it that you want us to build our own library (e.g in Android studio) having downloaded your GitHub code as a zip and then editing the relevant .sh document? For android, is it possible to disable certain features/libraries (i.e anything that is not required for Android) in build.gradle instead?

**Comment by tanersener** [comment] 2020-06-16 23:56
Editing `.sh` files, disabling not required components and enabling only necessary ones is the only way to have the smallest binaries possible. I know it is not easy for everyone. That's why prebuilt binaries are published. Use them if you don't want to work with `.sh` files. 

Doing the same thing from `build.gradle` is not possible at the moment. Technically, it is possible but a lot of effort is needed for that. And that would be a good example for `over-engineering`.

**Comment by alexcohn** [comment] 2020-09-01 12:57
Can this be marked duplicate of https://github.com/tanersener/mobile-ffmpeg/issues/428 ?

**Comment by tanersener** [comment] 2020-09-03 20:28
Added the duplicate label. I agree. It is the duplicate of #428.

**Closed** 2020-09-11 00:18 UTC
Labels: duplicate, no-issue-activity
