### ISSUE TITLE
Incredibly slow performance - decode stream camera captured MOV files

### ISSUE THREAD

**Issue by felixisto** [tanersener/mobile-ffmpeg#415] opened 2020-05-07 17:05 UTC
I am having an issue playing MOV camera captured files from an iPhone. My FFMPEG implementation has no problem playing most file formats, this issue is exclusive only for camera captured MOV.

When trying to open the file, I can see in the logs that many requests are made, each requests decoding only one frame, before making a new request which results the video being buffered extremely slowly. It takes roughly a minute to buffer about a few seconds of the video.

Another thing to mention is that the very same problematic file is played without an issue locally. The problem is when trying to decode while streaming.

I compiled my code on Xcode 11, iOS SDK 13, with cocoapods mobile-ffmpeg-https 4.2.

My code is very standard, I just open the file with avformat_open_input() and then read av_read_frame() and decode with avcodec_send_packet(). There are no custom options that I use for avformat_open_input.

Logs for opening the file
```
// [tls] First Request is made here
// [tls] First Request response headers are here
Probing mov,mp4,m4a,3gp,3g2,mj2 score:100 size:2048
Probing mp3 score:1 size:2048
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'ftyp' parent:'root' sz: 20 8 32429860
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] ISO: File Type Major Brand: qt  
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'wide' parent:'root' sz: 8 28 32429860
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'mdat' parent:'root' sz: 32420045 36 32429860
// [tls] 2nd Request is made here
// [tls] 2nd Request response headers are here
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'moov' parent:'root' sz: 9787 32420081 32429860
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'mvhd' parent:'moov' sz: 108 8 9779
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] time scale = 600
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'trak' parent:'moov' sz: 3596 116 9779
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'tkhd' parent:'trak' sz: 92 8 3588
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'tapt' parent:'trak' sz: 68 100 3588
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'edts' parent:'trak' sz: 36 168 3588
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'elst' parent:'edts' sz: 28 8 28
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] track[0].edit_count = 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] duration=10100 time=0 rate=1.000000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'mdia' parent:'trak' sz: 3392 204 3588
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'mdhd' parent:'mdia' sz: 32 8 3384
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'hdlr' parent:'mdia' sz: 49 40 3384
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] ctype=mhlr
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stype=vide
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'minf' parent:'mdia' sz: 3303 89 3384
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'vmhd' parent:'minf' sz: 20 8 3295
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'hdlr' parent:'minf' sz: 56 28 3295
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] ctype=dhlr
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stype=alis
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'dinf' parent:'minf' sz: 36 84 3295
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'dref' parent:'dinf' sz: 28 8 28
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] Unknown dref type 0x73696c61 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'stbl' parent:'minf' sz: 3183 120 3295
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'stsd' parent:'stbl' sz: 306 8 3175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] size=290 4CC=avc1 codec_type=0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'avcC' parent:'stsd' sz: 182 8 204
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'colr' parent:'stsd' sz: 18 190 204
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] nclc: pri 1 trc 1 matrix 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'stts' parent:'stbl' sz: 24 314 3175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] track[0].stts.entries = 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] sample_count=505, sample_duration=20
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'stss' parent:'stbl' sz: 84 338 3175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] keyframe_count = 17
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'sdtp' parent:'stbl' sz: 517 422 3175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'stsc' parent:'stbl' sz: 52 939 3175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] track[0].stsc.entries = 3
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'stsz' parent:'stbl' sz: 2040 991 3175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] sample_size = 0 sample_count = 505
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] type:'stco' parent:'stbl' sz: 152 3031 3175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] AVIndex stream 0, sample 0, offset 649b, dts 0, size 181863, distance 0, keyframe 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] AVIndex stream 0, sample 1, offset 32b02, dts 20, size 69367, distance 1, keyframe 0
// ...
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'localhost/Videos/Test/test.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2019-04-14T08:17:03.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 7
    com.apple.quicktime.software: 12.2
    com.apple.quicktime.creationdate: 2019-04-14T11:17:03+0300
  Duration: 00:00:16.83, bitrate: N/A
    Stream #0:0(und), 0, 1/600: Video: h264, 1 reference frame (avc1 / 0x31637661), none(bt709), 1920x1080 (0x0), 0/1, 15301 kb/s, 30 fps, 30 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2019-04-14T08:17:03.000000Z
      handler_name    : Core Media Video
      encoder         : H.264
    Stream #0:1(und), 0, 1/44100: Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, 100 kb/s (default)
    Metadata:
      creation_time   : 2019-04-14T08:17:03.000000Z
      handler_name    : Core Media Audio
    Stream #0:2(und), 0, 1/600: Data: none (mebx / 0x7862656D), 0/1, 0 kb/s (default)
    Metadata:
      creation_time   : 2019-04-14T08:17:03.000000Z
      handler_name    : Core Media Metadata
    Stream #0:3(und), 0, 1/600: Data: none (mebx / 0x7862656D), 0/1, 0 kb/s (default)
    Metadata:
      creation_time   : 2019-04-14T08:17:03.000000Z
      handler_name    : Core Media Metadata
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] Before avformat_find_stream_info() pos: 32429860 bytes read:26171 seeks:1 nb_streams:4
[h264 @ 0x114925600] nal_unit_type: 7(SPS), nal_ref_idc: 1
[h264 @ 0x114925600] nal_unit_type: 8(PPS), nal_ref_idc: 1
// [tls] Request is made here
// [tls] Request response headers are here
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x115918e00] stream 0, sample 4, dts 133333
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x115918e00] stream 1, sample 48, dts 1114558
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x115918e00] stream 2, sample 1, dts 2666667
[h264 @ 0x116080200] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
// [tls] Request is made here
// [tls] Request response headers are here
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x115918e00] stream 0, sample 4, dts 133333
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x115918e00] stream 1, sample 48, dts 1114558
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x115918e00] stream 2, sample 1, dts 2666667
[h264 @ 0x116080200] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
// [tls] Request is made here
// [tls] Request response headers are here
// ...
```
The decoders are then opened, and I start reading with av_read_frame().
FFMPEG seems to read only one frame, before closing the request and making a new one.
Logs:

```
// Request response
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stream 0, sample 3, dts 100000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stream 1, sample 47, dts 1091338
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stream 0, sample 3, dts 100000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stream 1, sample 48, dts 1114558
// New request made
// Request response
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stream 0, sample 4, dts 133333
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1150cd600] stream 1, sample 48, dts 1114558
[h264 @ 0x11490f800] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
// New request made
// Request response
```

I tried messing around with the probesize, analyzeduration, any pretty much any option and flag for AVFormatCodec. I tried downgrading to 3.2 ffmpeg, tried ffmpeg-full, tried 4.3.1 ffmpeg (latest one that I can compile) and none of those work.

These MOV files play fine locally (read from the iPhone storage), and my ffmpeg implementation works with other file formats without any issues. Its only the iPhone camera captured files that are problematic, specifically when streaming.

With other files formats, only ONE network request is made, for the whole playback.

When comparing the logs with other files that work, the only difference, besides the multiple network requests, is "Probing mp3 score:1 size:2048".

**Comment by tanersener** [comment] 2020-05-07 22:01
I'd like to help but I really don't have any idea.

**Comment by felixisto** [comment] 2020-05-07 22:42
Assuming the issue is not from my code, shouldn't this be a bug? FFMPPEG supports MOV.

**Comment by tanersener** [comment] 2020-05-07 23:59
I don't think it is possible to say that this is a bug or not without understanding what the issue is.

Also, there are a lot of details that are not clear about what you are doing. For example:
- `... issue playing MOV camera captured files`: `MobileFFmpeg` does not have a file playing functionality. How do you use `MobileFFmpeg`?
- `My FFMPEG implementation ...`: What is your `FFMPEG` implementation? You mentioned that you tried `downgrading to 3.2 ffmpeg`. How your tested this with `MobileFFmpeg` ?
- `My code is very standard...`:  I understand what you mean but I'm not an expert on native ffmpeg API. So I can't tell you whether you're doing something wrong or not. Why don't you ask this to `ffmpeg` mailing list.

**Comment by felixisto** [comment] 2020-05-08 09:51
The issue is that `av_read_frame()` makes a network request almost every time it gets called.
Even `avformat_open_input() ` makes multiple network requests just open the AVFormatContext.
Because of this, the performance is extremely bad, to the point where I cannot use ffmpeg to read these MOV files for my video player (I am writing a streaming video player that uses FFMPEG mobile).

This issue does not happen for any other files, including other non-camera MOV files.

Here is my code: https://github.com/felixisto/TestFFMPEG/blob/master/TestFFMPEG/ViewController.m

Full logs for the broken.mov file:
https://github.com/felixisto/TestFFMPEG/blob/master/01-logs-broken.mov.txt

Full logs for the works.mov file:
https://github.com/felixisto/TestFFMPEG/blob/master/01-logs-works.mov.txt

The videos:
https://github.com/felixisto/TestFFMPEG/tree/master/samples

I will try to email ffmpeg. I tried asking here first, because this is mobile specific ffmpeg.

**Comment by tanersener** [comment] 2020-05-08 10:27
Thanks for sharing this information. I guess someone who is familiar with ffmpeg API can help you about this.

**Comment by felixisto** [comment] 2020-05-08 10:42
I don't know how to make a bug report to ffmpeg. It asks me to register, and then asks me for a project name.
Also according to https://ffmpeg.org/bugreports.html, the only reports I can write are about ffmpeg commands, so that does not cover my issue (unless I find a way to replicate this with a command).

**Comment by tanersener** [comment] 2020-05-08 11:05
I know you're convinced that this is a bug but how about asking this to [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list? They can help you identify the issue. Also they can help you about creating a bug report.

**Comment by felixisto** [comment] 2020-05-08 17:58
I have sent an email for subscription to the mailing list.

Also I found sorta of hack fix. I set the AVFormatContext nb_streams to 1 (it is 4 for the broken file). I thought the the reason why its making all of these requests is due to the multiple streams. This partially resolved the issue, but now I've got no audio. Setting the nb_streams to 2 does not change anything.

**Comment by kristiyan-butev-axway** [comment] 2020-07-03 18:31
Hello, I found a slightly better fix, where you also get audio:

Set the io_open callback of the AVFormatContext to your own function, and then when that is called, after you call the default io_open you change the buffer size

```
static int (*IO_OPEN_DEFAULT)(struct AVFormatContext *s, AVIOContext **pb, const char *url, int flags, AVDictionary **options);

int IO_OPEN_OVERRIDE(struct AVFormatContext *s, AVIOContext **pb, const char *url, int flags, AVDictionary **options) {
    int result = IO_OPEN_DEFAULT(s, pb, url, flags, options);
    pb[0]->buffer_size = 41239179;
    return result;
}
```

This fixes the issue. The value you set it to is usually very large (20 to 40MB). You can get that value from the second network request bytes range when you are opening the format context (first network request is made with bytes range 0-* and then the second network request is made with bytes range XXXX-* where XXXX should be the buffer size).

The reason why this fixes the issue, is because by buffering all of that data, aviocontext no longer needs to make a new network request to get the audio data. The audio data is already buffered (or at least the first position is).

There might be a better way to fix this issue, it seems like apple MOV files separate their video and audio data with these massive chunks for some reason and that causes ffmpeg to make a million network requests, for each frame.

@tanersener You can close this now.

**Comment by felixisto** [comment] 2020-07-03 18:33
Hello, I found a slightly better fix, where you also get audio:
 
Set the io_open callback of the AVFormatContext to your own function, and then when that is called, after you call the default io_open you change the buffer size
 
```
static int (*IO_OPEN_DEFAULT)(struct AVFormatContext *s, AVIOContext **pb, const char *url, int flags, AVDictionary **options);
 
int IO_OPEN_OVERRIDE(struct AVFormatContext *s, AVIOContext **pb, const char *url, int flags, AVDictionary **options) {
    int result = IO_OPEN_DEFAULT(s, pb, url, flags, options);
    pb[0]->buffer_size = 41239179;
    return result;
}
```
 
This fixes the issue. The value you set it to is usually very large (20 to 40MB). You can get that value from the second network request bytes range when you are opening the format context (first network request is made with bytes range 0-* and then the second network request is made with bytes range XXXX-* where XXXX should be the buffer size).
 
The reason why this fixes the issue, is because by buffering all of that data, aviocontext no longer needs to make a new network request to get the audio data. The audio data is already buffered (or at least the first position is).
 
There might be a better way to fix this issue, it seems like apple MOV files separate their video and audio data with these massive chunks for some reason and that causes ffmpeg to make a million network requests, for each frame.

@tanersener You can close this issue now.

**Comment by felixisto** [comment] 2020-07-03 18:33
I did not get any response from the ffmpeg mail list thing.

**Comment by tanersener** [comment] 2020-07-06 16:12
Thanks for sharing the solution @felixisto. I'm sure it will help other people facing a similar issue.

**Closed by tanersener** 2020-07-06 16:12 UTC
Labels: ffmpeg-question
