### ISSUE TITLE
How to display the Camera Preview in a UIView in iOS?

### ISSUE THREAD

**Issue by pushsoftdev** [tanersener/mobile-ffmpeg#332] opened 2020-01-30 17:25 UTC
I'm using the following command to stream the video to a local UDP port in my iOS project.

`-f avfoundation -r 30 -video_size 640x480 -pixel_format bgr0 -i \"default:default\" -preset ultrafast -c:v h264_videotoolbox -c:a mp2 -tune zerolatency -b 900k -f tee -map 0:v -map 0:a \"%@|[f=mpegts]udp://127.0.0.1:43000/`

While the streaming is happening, I want to display the camera preview in my view.. Pls let me know. Thank You

**Comment by tanersener** [comment] 2020-01-30 19:36
Duplicate of #146

**Comment by asifhabib** [comment] 2020-02-07 10:14
Any update on this issue?

**Closed** 2020-03-15 22:14 UTC
Labels: duplicate
