### ISSUE TITLE
getLastCommandOutput() returns incomplete result after execution 

### ISSUE THREAD

**Issue by iammert** [tanersener/mobile-ffmpeg#211] opened 2019-08-21 12:03 UTC
**Description**
`FFmpeg.getLastCommandOutput()` returns incomplete result after execution. But `Config.enableLogCallback{ }` still emitting values and complete values after execution is completed.

**Expected behavior**
I think `FFmpeg.getLastCommandOutput()` should return complete result if it is called after `FFmpeg.execute()` operation is complete. And also `Config.enableLogCallback{ }` should stop emitting value after `FFmpeg.execute()` operation returns a value.

**Code Sample**
```kotlin
Config.enableLogCallback {
        Log.v(TAG, "Logging: ${FFmpeg.getLastCommandOutput().contains("Audio")"}
}
        
val result = FFmpeg.execute(command)
Log.v(TAG, "Result: ${FFmpeg.getLastCommandOutput().contains("Audio")"}
```

Output: 
```
Logging: false
...
Logging: false
Result: false
Logging: false
...
Logging: true
...
Logging: true
```

**Environment**
 - Platform: Android
 - Architecture: arm64-v8a

**Comment by tanersener** [comment] 2019-08-21 13:52
I never experienced this behavior but technically it can happen. Unfortunately, there is not an easy solution for this.

`MobileFFmpeg` uses an internal queue to collect `ffmpeg` logs and distributes collected logs using a dedicated thread (callback thread). This dedicated thread is responsible of invoking both `Log Callback` and `Statistics Callback` functions. 

In your case, when `execute` process has finished, there are still `ffmpeg` logs waiting in the queue. They are not distributed by the callback thread and `last command output` is not complete yet. This can happen if `Callback Thread` can not distribute collected logs fast enough because of the following reasons: 

1. Your command generates too much logs
2. You are doing too much work in `LogCallback` and/or `StatisticsCallback` callback functions

Can you give me more details about the command you use? I tried to reproduce this issue locally but I wasn't successful.

**Comment by iammert** [comment] 2019-08-22 07:15
Actually, I am not doing too much work inside LogCallback. I am just notifying listener to cancel the notification. So we can eliminate the second reason.

So when we back to the first reason you gave, It might be the reason. We are using FFmpeg in our Video Editor project which is not a simple video editor. So user can combine, crop, filter, resize videos and audios, also command script has lots of input including, gifs, overlay images, audios, etc. 

But, besides all, I think, execute() operation has to wait for all other logging threads or drop invalid logs and emit last possible and complete log when it is completed. By the way, I don't know if it is possible on your library side.

I believe you can reproduce this issue locally by using my command script, but as I said before, I have lots of params. So It is really hard to attach all files with my script here. But here is the script in case you can find some clue about the situation.

I did a little hack. (Thread.sleep(400) after execute() command has finished) It is working for now.  But it is a workaround. I am really appreciated If you find out a fix for the problem.

**Comment by tanersener** [comment] 2019-08-23 05:44
Thanks. 

First versions of the library didn't have a queue and a callback thread. So technically, `execute` was waiting for all logging to complete. The problem was that design was decreasing execution time significantly and users who wasn't interested in logs complained too much about the speed. This is why I implemented a queue and a callback thread. 

I don't want to change the current design but I agree that `getLastCommandOutput` should be improved and always return full output. I'll work on it.

However, improving `getLastCommandOutput` won't solve your issues and you'll still need to sleep/wait after `execute`. I don't know how can I improve that. I have a similar case inside the library and I'm solving it inside the `Config.systemExecute` function. It is doing what you're currently doing.

**Comment by tanersener** [comment] 2019-08-28 15:23
Fixed in development branch

**Closed** 2019-10-27 15:14 UTC
Labels: enhancement, fixed
